/*
 * settings_glade.h
 * 
 * Copyright 2013-2017 AmatCoder
 * 
 * This file is part of Mednaffe.
 * 
 * Mednaffe is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Mednaffe is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Mednaffe; if not, see <http://www.gnu.org/licenses/>.
 * 
 */
 
#ifndef SETTINGS_GLADE_H
#define SETTINGS_GLADE_H

static const char *settings_glade =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<interface>\n"
"<requires lib=\"gtk+\" version=\"2.24\"/>\n"
"<!-- interface-naming-policy project-wide -->\n"
"<object class=\"GtkAdjustment\" id=\"adjustment1\">\n"
"<property name=\"lower\">1</property>\n"
"<property name=\"upper\">99</property>\n"
"<property name=\"value\">1</property>\n"
"<property name=\"step_increment\">1</property>\n"
"<property name=\"page_increment\">10</property>\n"
"</object>\n"
"<object class=\"GtkDialog\" id=\"dialog2\">\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"border_width\">5</property>\n"
"<property name=\"title\" translatable=\"yes\">Folder Setup</property>\n"
"<property name=\"resizable\">False</property>\n"
"<property name=\"modal\">True</property>\n"
"<property name=\"destroy_with_parent\">True</property>\n"
"<property name=\"type_hint\">dialog</property>\n"
"<signal name=\"delete-event\" handler=\"close_folder_settings\" swapped=\"no\"/>\n"
"<child internal-child=\"vbox\">\n"
"<object class=\"GtkVBox\" id=\"dialog-vbox2\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"spacing\">2</property>\n"
"<child>\n"
"<object class=\"GtkFrame\" id=\"frame2\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"border_width\">8</property>\n"
"<property name=\"label_xalign\">0</property>\n"
"<property name=\"shadow_type\">none</property>\n"
"<child>\n"
"<object class=\"GtkAlignment\" id=\"alignment2\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"left_padding\">12</property>\n"
"<child>\n"
"<object class=\"GtkVBox\" id=\"vbox1\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"border_width\">8</property>\n"
"<property name=\"spacing\">8</property>\n"
"<child>\n"
"<object class=\"GtkCheckButton\" id=\"scan\">\n"
"<property name=\"label\" translatable=\"yes\">Scan this folder recursively (to show files from subdirectories)</property>\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">True</property>\n"
"<property name=\"receives_default\">False</property>\n"
"<property name=\"draw_indicator\">True</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">0</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkCheckButton\" id=\"hide_ext\">\n"
"<property name=\"label\" translatable=\"yes\">Hide file extensions</property>\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">True</property>\n"
"<property name=\"receives_default\">False</property>\n"
"<property name=\"draw_indicator\">True</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">1</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkHBox\" id=\"hbox2\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<child>\n"
"<object class=\"GtkLabel\" id=\"label4\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"label\" translatable=\"yes\">Comma-separated list of filetypes to show (i.e. zip,cue,m3u): </property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">0</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkEntry\" id=\"filters\">\n"
"<property name=\"width_request\">300</property>\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">True</property>\n"
"<property name=\"invisible_char\">•</property>\n"
"<property name=\"primary_icon_activatable\">False</property>\n"
"<property name=\"secondary_icon_activatable\">False</property>\n"
"<property name=\"primary_icon_sensitive\">True</property>\n"
"<property name=\"secondary_icon_sensitive\">True</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">1</property>\n"
"</packing>\n"
"</child>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">2</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkHBox\" id=\"hbox5\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<child>\n"
"<object class=\"GtkLabel\" id=\"label8\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"label\" translatable=\"yes\">Path to game snapshots folder (A): </property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">0</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkEntry\" id=\"screen_a\">\n"
"<property name=\"width_request\">400</property>\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">True</property>\n"
"<property name=\"invisible_char\">•</property>\n"
"<property name=\"primary_icon_activatable\">False</property>\n"
"<property name=\"secondary_icon_activatable\">False</property>\n"
"<property name=\"primary_icon_sensitive\">True</property>\n"
"<property name=\"secondary_icon_sensitive\">True</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">1</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkButton\" id=\"button5\">\n"
"<property name=\"label\">gtk-open</property>\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">True</property>\n"
"<property name=\"receives_default\">True</property>\n"
"<property name=\"use_stock\">True</property>\n"
"<signal name=\"clicked\" handler=\"on_button_snaps_folder\" object=\"screen_a\" swapped=\"no\"/>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">2</property>\n"
"</packing>\n"
"</child>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">3</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkHBox\" id=\"hbox4\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<child>\n"
"<object class=\"GtkLabel\" id=\"label7\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"label\" translatable=\"yes\">Path to game snapshots folder (B): </property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">0</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkEntry\" id=\"screen_b\">\n"
"<property name=\"width_request\">400</property>\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">True</property>\n"
"<property name=\"invisible_char\">•</property>\n"
"<property name=\"primary_icon_activatable\">False</property>\n"
"<property name=\"secondary_icon_activatable\">False</property>\n"
"<property name=\"primary_icon_sensitive\">True</property>\n"
"<property name=\"secondary_icon_sensitive\">True</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">1</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkButton\" id=\"button4\">\n"
"<property name=\"label\">gtk-open</property>\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">True</property>\n"
"<property name=\"receives_default\">True</property>\n"
"<property name=\"use_stock\">True</property>\n"
"<signal name=\"clicked\" handler=\"on_button_snaps_folder\" object=\"screen_b\" swapped=\"no\"/>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">2</property>\n"
"</packing>\n"
"</child>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">4</property>\n"
"</packing>\n"
"</child>\n"
"</object>\n"
"</child>\n"
"</object>\n"
"</child>\n"
"<child type=\"label\">\n"
"<object class=\"GtkLabel\" id=\"folder_label\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"label\" translatable=\"yes\">&lt;b&gt;Folder Setup&lt;/b&gt;</property>\n"
"<property name=\"use_markup\">True</property>\n"
"</object>\n"
"</child>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">0</property>\n"
"</packing>\n"
"</child>\n"
"<child internal-child=\"action_area\">\n"
"<object class=\"GtkHButtonBox\" id=\"dialog-action_area2\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"layout_style\">end</property>\n"
"<child>\n"
"<object class=\"GtkButton\" id=\"cancel\">\n"
"<property name=\"label\">gtk-cancel</property>\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">True</property>\n"
"<property name=\"receives_default\">True</property>\n"
"<property name=\"use_stock\">True</property>\n"
"<signal name=\"clicked\" handler=\"cancel_folder_settings\" swapped=\"no\"/>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">False</property>\n"
"<property name=\"position\">0</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkButton\" id=\"apply\">\n"
"<property name=\"label\">gtk-apply</property>\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">True</property>\n"
"<property name=\"receives_default\">True</property>\n"
"<property name=\"use_stock\">True</property>\n"
"<signal name=\"clicked\" handler=\"apply_folder_settings\" swapped=\"no\"/>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">False</property>\n"
"<property name=\"position\">1</property>\n"
"</packing>\n"
"</child>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">True</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">1</property>\n"
"</packing>\n"
"</child>\n"
"</object>\n"
"</child>\n"
"<action-widgets>\n"
"<action-widget response=\"0\">cancel</action-widget>\n"
"<action-widget response=\"0\">apply</action-widget>\n"
"</action-widgets>\n"
"</object>\n"
"<object class=\"GtkDialog\" id=\"dialog3\">\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"border_width\">5</property>\n"
"<property name=\"title\" translatable=\"yes\">Folders Setup</property>\n"
"<property name=\"modal\">True</property>\n"
"<property name=\"default_width\">640</property>\n"
"<property name=\"default_height\">480</property>\n"
"<property name=\"destroy_with_parent\">True</property>\n"
"<property name=\"type_hint\">dialog</property>\n"
"<signal name=\"delete-event\" handler=\"close_folder_list\" swapped=\"no\"/>\n"
"<child internal-child=\"vbox\">\n"
"<object class=\"GtkVBox\" id=\"dialog-vbox4\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<child internal-child=\"action_area\">\n"
"<object class=\"GtkHButtonBox\" id=\"dialog-action_area4\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"layout_style\">edge</property>\n"
"<child>\n"
"<object class=\"GtkButton\" id=\"button2\">\n"
"<property name=\"label\">gtk-remove</property>\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">True</property>\n"
"<property name=\"receives_default\">True</property>\n"
"<property name=\"use_stock\">True</property>\n"
"<signal name=\"clicked\" handler=\"remove_folder\" swapped=\"no\"/>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">False</property>\n"
"<property name=\"position\">0</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkButton\" id=\"button3\">\n"
"<property name=\"label\" translatable=\"yes\">Setup</property>\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">True</property>\n"
"<property name=\"receives_default\">True</property>\n"
"<signal name=\"clicked\" handler=\"on_folder_setup\" swapped=\"no\"/>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">False</property>\n"
"<property name=\"position\">1</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkButton\" id=\"button6\">\n"
"<property name=\"label\">gtk-close</property>\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">True</property>\n"
"<property name=\"receives_default\">True</property>\n"
"<property name=\"use_stock\">True</property>\n"
"<signal name=\"clicked\" handler=\"cancel_folder_list\" swapped=\"no\"/>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">False</property>\n"
"<property name=\"position\">2</property>\n"
"</packing>\n"
"</child>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">False</property>\n"
"<property name=\"position\">0</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkFrame\" id=\"frame4\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"label_xalign\">0</property>\n"
"<property name=\"shadow_type\">none</property>\n"
"<child>\n"
"<object class=\"GtkAlignment\" id=\"alignment4\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"left_padding\">12</property>\n"
"<property name=\"right_padding\">12</property>\n"
"<child>\n"
"<object class=\"GtkVBox\" id=\"vbox2\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<child>\n"
"<object class=\"GtkLabel\" id=\"label16\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"label\" translatable=\"yes\">Drag and drop to reorder folders.</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">False</property>\n"
"<property name=\"padding\">8</property>\n"
"<property name=\"position\">0</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkScrolledWindow\" id=\"scrolledwindow1\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">True</property>\n"
"<property name=\"border_width\">2</property>\n"
"<property name=\"hscrollbar_policy\">automatic</property>\n"
"<property name=\"vscrollbar_policy\">automatic</property>\n"
"<child>\n"
"<object class=\"GtkTreeView\" id=\"treeview1\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">True</property>\n"
"<property name=\"headers_clickable\">False</property>\n"
"<property name=\"reorderable\">True</property>\n"
"<child>\n"
"<object class=\"GtkTreeViewColumn\" id=\"treeviewcolumn1\">\n"
"<property name=\"title\" translatable=\"yes\">Folders</property>\n"
"<child>\n"
"<object class=\"GtkCellRendererText\" id=\"cellrenderertext1\"/>\n"
"<attributes>\n"
"<attribute name=\"text\">0</attribute>\n"
"</attributes>\n"
"</child>\n"
"</object>\n"
"</child>\n"
"</object>\n"
"</child>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">True</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">1</property>\n"
"</packing>\n"
"</child>\n"
"</object>\n"
"</child>\n"
"</object>\n"
"</child>\n"
"<child type=\"label\">\n"
"<object class=\"GtkLabel\" id=\"label3\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"label\" translatable=\"yes\">&lt;b&gt;Folders Setup&lt;/b&gt;</property>\n"
"<property name=\"use_markup\">True</property>\n"
"</object>\n"
"</child>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">True</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">1</property>\n"
"</packing>\n"
"</child>\n"
"</object>\n"
"</child>\n"
"<action-widgets>\n"
"<action-widget response=\"0\">button2</action-widget>\n"
"<action-widget response=\"0\">button3</action-widget>\n"
"<action-widget response=\"0\">button6</action-widget>\n"
"</action-widgets>\n"
"</object>\n"
"<object class=\"GtkDialog\" id=\"dialog4\">\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"border_width\">5</property>\n"
"<property name=\"resizable\">False</property>\n"
"<property name=\"modal\">True</property>\n"
"<property name=\"type_hint\">dialog</property>\n"
"<signal name=\"destroy-event\" handler=\"close_bios_check\" swapped=\"no\"/>\n"
"<child internal-child=\"vbox\">\n"
"<object class=\"GtkVBox\" id=\"dialog-vbox6\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"spacing\">2</property>\n"
"<child internal-child=\"action_area\">\n"
"<object class=\"GtkHButtonBox\" id=\"dialog-action_area6\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"layout_style\">end</property>\n"
"<child>\n"
"<object class=\"GtkButton\" id=\"button7\">\n"
"<property name=\"label\">gtk-close</property>\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">True</property>\n"
"<property name=\"receives_default\">True</property>\n"
"<property name=\"use_stock\">True</property>\n"
"<signal name=\"clicked\" handler=\"cancel_bios_check\" swapped=\"no\"/>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">False</property>\n"
"<property name=\"position\">0</property>\n"
"</packing>\n"
"</child>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">True</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">0</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkFrame\" id=\"frame3\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"label_xalign\">0</property>\n"
"<property name=\"shadow_type\">none</property>\n"
"<child>\n"
"<object class=\"GtkAlignment\" id=\"alignment3\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"top_padding\">6</property>\n"
"<property name=\"bottom_padding\">6</property>\n"
"<property name=\"left_padding\">12</property>\n"
"<child>\n"
"<object class=\"GtkTable\" id=\"table1\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"n_rows\">7</property>\n"
"<property name=\"n_columns\">3</property>\n"
"<property name=\"column_spacing\">24</property>\n"
"<property name=\"row_spacing\">6</property>\n"
"<child>\n"
"<object class=\"GtkLabel\" id=\"label9\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"xalign\">0</property>\n"
"<property name=\"label\" translatable=\"yes\">Atari Lynx:</property>\n"
"</object>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkLabel\" id=\"label10\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"xalign\">0</property>\n"
"<property name=\"label\" translatable=\"yes\">PC-FX:</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"top_attach\">1</property>\n"
"<property name=\"bottom_attach\">2</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkLabel\" id=\"label11\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"xalign\">0</property>\n"
"<property name=\"label\" translatable=\"yes\">Sony Playstation (Europe):</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"top_attach\">2</property>\n"
"<property name=\"bottom_attach\">3</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkLabel\" id=\"label12\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"xalign\">0</property>\n"
"<property name=\"label\" translatable=\"yes\">Sony Playstation (Japan):</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"top_attach\">3</property>\n"
"<property name=\"bottom_attach\">4</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkLabel\" id=\"label13\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"xalign\">0</property>\n"
"<property name=\"label\" translatable=\"yes\">Sony Playstation (North America):</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"top_attach\">4</property>\n"
"<property name=\"bottom_attach\">5</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkLabel\" id=\"label14\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"xalign\">0</property>\n"
"<property name=\"label\" translatable=\"yes\">Sega Saturn (North America and Europe):</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"top_attach\">5</property>\n"
"<property name=\"bottom_attach\">6</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkLabel\" id=\"label15\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"xalign\">0</property>\n"
"<property name=\"label\" translatable=\"yes\">Sega Saturn (Japan):</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"top_attach\">6</property>\n"
"<property name=\"bottom_attach\">7</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkLabel\" id=\"label-lynx.bios\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"has_tooltip\">True</property>\n"
"<property name=\"xalign\">0</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"left_attach\">1</property>\n"
"<property name=\"right_attach\">2</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkLabel\" id=\"label-pcfx.bios\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"has_tooltip\">True</property>\n"
"<property name=\"xalign\">0</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"left_attach\">1</property>\n"
"<property name=\"right_attach\">2</property>\n"
"<property name=\"top_attach\">1</property>\n"
"<property name=\"bottom_attach\">2</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkLabel\" id=\"label-psx.bios_eu\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"has_tooltip\">True</property>\n"
"<property name=\"xalign\">0</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"left_attach\">1</property>\n"
"<property name=\"right_attach\">2</property>\n"
"<property name=\"top_attach\">2</property>\n"
"<property name=\"bottom_attach\">3</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkLabel\" id=\"label-psx.bios_jp\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"has_tooltip\">True</property>\n"
"<property name=\"xalign\">0</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"left_attach\">1</property>\n"
"<property name=\"right_attach\">2</property>\n"
"<property name=\"top_attach\">3</property>\n"
"<property name=\"bottom_attach\">4</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkLabel\" id=\"label-psx.bios_na\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"has_tooltip\">True</property>\n"
"<property name=\"xalign\">0</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"left_attach\">1</property>\n"
"<property name=\"right_attach\">2</property>\n"
"<property name=\"top_attach\">4</property>\n"
"<property name=\"bottom_attach\">5</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkLabel\" id=\"label-ss.bios_na_eu\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"has_tooltip\">True</property>\n"
"<property name=\"xalign\">0</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"left_attach\">1</property>\n"
"<property name=\"right_attach\">2</property>\n"
"<property name=\"top_attach\">5</property>\n"
"<property name=\"bottom_attach\">6</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkLabel\" id=\"label-ss.bios_jp\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"has_tooltip\">True</property>\n"
"<property name=\"xalign\">0</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"left_attach\">1</property>\n"
"<property name=\"right_attach\">2</property>\n"
"<property name=\"top_attach\">6</property>\n"
"<property name=\"bottom_attach\">7</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkImage\" id=\"image-lynx.bios\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"has_tooltip\">True</property>\n"
"<property name=\"xalign\">0</property>\n"
"<property name=\"stock\">gtk-missing-image</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"left_attach\">2</property>\n"
"<property name=\"right_attach\">3</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkImage\" id=\"image-pcfx.bios\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"has_tooltip\">True</property>\n"
"<property name=\"xalign\">0</property>\n"
"<property name=\"stock\">gtk-missing-image</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"left_attach\">2</property>\n"
"<property name=\"right_attach\">3</property>\n"
"<property name=\"top_attach\">1</property>\n"
"<property name=\"bottom_attach\">2</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkImage\" id=\"image-psx.bios_eu\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"has_tooltip\">True</property>\n"
"<property name=\"xalign\">0</property>\n"
"<property name=\"stock\">gtk-missing-image</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"left_attach\">2</property>\n"
"<property name=\"right_attach\">3</property>\n"
"<property name=\"top_attach\">2</property>\n"
"<property name=\"bottom_attach\">3</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkImage\" id=\"image-psx.bios_jp\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"has_tooltip\">True</property>\n"
"<property name=\"xalign\">0</property>\n"
"<property name=\"stock\">gtk-missing-image</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"left_attach\">2</property>\n"
"<property name=\"right_attach\">3</property>\n"
"<property name=\"top_attach\">3</property>\n"
"<property name=\"bottom_attach\">4</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkImage\" id=\"image-psx.bios_na\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"has_tooltip\">True</property>\n"
"<property name=\"xalign\">0</property>\n"
"<property name=\"stock\">gtk-missing-image</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"left_attach\">2</property>\n"
"<property name=\"right_attach\">3</property>\n"
"<property name=\"top_attach\">4</property>\n"
"<property name=\"bottom_attach\">5</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkImage\" id=\"image-ss.bios_na_eu\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"has_tooltip\">True</property>\n"
"<property name=\"xalign\">0</property>\n"
"<property name=\"stock\">gtk-missing-image</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"left_attach\">2</property>\n"
"<property name=\"right_attach\">3</property>\n"
"<property name=\"top_attach\">5</property>\n"
"<property name=\"bottom_attach\">6</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkImage\" id=\"image-ss.bios_jp\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"has_tooltip\">True</property>\n"
"<property name=\"xalign\">0</property>\n"
"<property name=\"stock\">gtk-missing-image</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"left_attach\">2</property>\n"
"<property name=\"right_attach\">3</property>\n"
"<property name=\"top_attach\">6</property>\n"
"<property name=\"bottom_attach\">7</property>\n"
"</packing>\n"
"</child>\n"
"</object>\n"
"</child>\n"
"</object>\n"
"</child>\n"
"<child type=\"label\">\n"
"<object class=\"GtkLabel\" id=\"label6\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"label\" translatable=\"yes\">&lt;b&gt;Bios Check&lt;/b&gt;</property>\n"
"<property name=\"use_markup\">True</property>\n"
"</object>\n"
"</child>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">1</property>\n"
"</packing>\n"
"</child>\n"
"</object>\n"
"</child>\n"
"<action-widgets>\n"
"<action-widget response=\"0\">button7</action-widget>\n"
"</action-widgets>\n"
"</object>\n"
"<object class=\"GtkListStore\" id=\"se_liststore\">\n"
"<columns>\n"
"<!-- column-name System -->\n"
"<column type=\"gchararray\"/>\n"
"<!-- column-name Show -->\n"
"<column type=\"gboolean\"/>\n"
"<!-- column-name gint1 -->\n"
"<column type=\"gint\"/>\n"
"</columns>\n"
"<data>\n"
"<row>\n"
"<col id=\"0\">Atary Lynx</col>\n"
"<col id=\"1\">True</col>\n"
"<col id=\"2\">0</col>\n"
"</row>\n"
"<row>\n"
"<col id=\"0\">GameBoy (Color)</col>\n"
"<col id=\"1\">True</col>\n"
"<col id=\"2\">1</col>\n"
"</row>\n"
"<row>\n"
"<col id=\"0\">GameBoy Advance</col>\n"
"<col id=\"1\">True</col>\n"
"<col id=\"2\">2</col>\n"
"</row>\n"
"<row>\n"
"<col id=\"0\">Neo Geo Pocket (Color)</col>\n"
"<col id=\"1\">True</col>\n"
"<col id=\"2\">3</col>\n"
"</row>\n"
"<row>\n"
"<col id=\"0\">Nintendo Entertainment System/Famicom</col>\n"
"<col id=\"1\">True</col>\n"
"<col id=\"2\">4</col>\n"
"</row>\n"
"<row>\n"
"<col id=\"0\">PC Engine (CD)/TurboGrafx 16 (CD)/SuperGrafx</col>\n"
"<col id=\"1\">True</col>\n"
"<col id=\"2\">5</col>\n"
"</row>\n"
"<row>\n"
"<col id=\"0\">PC-FX</col>\n"
"<col id=\"1\">True</col>\n"
"<col id=\"2\">6</col>\n"
"</row>\n"
"<row>\n"
"<col id=\"0\">Sega Game Gear</col>\n"
"<col id=\"1\">True</col>\n"
"<col id=\"2\">7</col>\n"
"</row>\n"
"<row>\n"
"<col id=\"0\">Sega Genesis/MegaDrive</col>\n"
"<col id=\"1\">True</col>\n"
"<col id=\"2\">8</col>\n"
"</row>\n"
"<row>\n"
"<col id=\"0\">Sega Master System</col>\n"
"<col id=\"1\">True</col>\n"
"<col id=\"2\">9</col>\n"
"</row>\n"
"<row>\n"
"<col id=\"0\">Sega Saturn</col>\n"
"<col id=\"1\">True</col>\n"
"<col id=\"2\">10</col>\n"
"</row>\n"
"<row>\n"
"<col id=\"0\">Sony PlayStation</col>\n"
"<col id=\"1\">True</col>\n"
"<col id=\"2\">11</col>\n"
"</row>\n"
"<row>\n"
"<col id=\"0\">Super Nintendo Entertainment System/Super Famicom</col>\n"
"<col id=\"1\">True</col>\n"
"<col id=\"2\">12</col>\n"
"</row>\n"
"<row>\n"
"<col id=\"0\">Virtual Boy</col>\n"
"<col id=\"1\">True</col>\n"
"<col id=\"2\">13</col>\n"
"</row>\n"
"<row>\n"
"<col id=\"0\">WonderSwan (Color)</col>\n"
"<col id=\"1\">True</col>\n"
"<col id=\"2\">14</col>\n"
"</row>\n"
"</data>\n"
"</object>\n"
"<object class=\"GtkDialog\" id=\"dialog1\">\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"border_width\">5</property>\n"
"<property name=\"title\" translatable=\"yes\">Preferences</property>\n"
"<property name=\"resizable\">False</property>\n"
"<property name=\"modal\">True</property>\n"
"<property name=\"destroy_with_parent\">True</property>\n"
"<property name=\"type_hint\">dialog</property>\n"
"<signal name=\"delete-event\" handler=\"close_prefs\" swapped=\"no\"/>\n"
"<child internal-child=\"vbox\">\n"
"<object class=\"GtkVBox\" id=\"dialog-vbox1\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"spacing\">2</property>\n"
"<child internal-child=\"action_area\">\n"
"<object class=\"GtkHButtonBox\" id=\"dialog-action_area1\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"layout_style\">end</property>\n"
"<child>\n"
"<object class=\"GtkButton\" id=\"button1\">\n"
"<property name=\"label\">gtk-close</property>\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">True</property>\n"
"<property name=\"receives_default\">True</property>\n"
"<property name=\"use_stock\">True</property>\n"
"<signal name=\"clicked\" handler=\"cancel_prefs\" swapped=\"no\"/>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">False</property>\n"
"<property name=\"position\">0</property>\n"
"</packing>\n"
"</child>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">True</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">0</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkNotebook\" id=\"notebook1\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">True</property>\n"
"<child>\n"
"<object class=\"GtkFrame\" id=\"frame18\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"border_width\">4</property>\n"
"<property name=\"label_xalign\">0</property>\n"
"<property name=\"shadow_type\">none</property>\n"
"<child>\n"
"<object class=\"GtkAlignment\" id=\"alignment21\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"left_padding\">12</property>\n"
"<child>\n"
"<object class=\"GtkVBox\" id=\"vbox28\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<child>\n"
"<object class=\"GtkCheckButton\" id=\"showtooltips\">\n"
"<property name=\"label\" translatable=\"yes\">Show tooltips</property>\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">True</property>\n"
"<property name=\"receives_default\">False</property>\n"
"<property name=\"has_tooltip\">True</property>\n"
"<property name=\"tooltip_text\" translatable=\"yes\">Tooltips are informative, but sometimes they can be annoying.\n"
"You can disable them here.</property>\n"
"<property name=\"active\">True</property>\n"
"<property name=\"draw_indicator\">True</property>\n"
"<signal name=\"toggled\" handler=\"on_showtooltips_toggled\" swapped=\"no\"/>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">0</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkCheckButton\" id=\"remembersize\">\n"
"<property name=\"label\" translatable=\"yes\">Remember window size</property>\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">True</property>\n"
"<property name=\"receives_default\">False</property>\n"
"<property name=\"active\">True</property>\n"
"<property name=\"draw_indicator\">True</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">1</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkVBox\" id=\"vbox26\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<child>\n"
"<object class=\"GtkLabel\" id=\"label71\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"xalign\">0</property>\n"
"<property name=\"label\" translatable=\"yes\">Action when launch:</property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"padding\">3</property>\n"
"<property name=\"position\">0</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkAlignment\" id=\"alignment20\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"left_padding\">12</property>\n"
"<child>\n"
"<object class=\"GtkVBox\" id=\"vbox27\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<child>\n"
"<object class=\"GtkRadioButton\" id=\"rbnothing\">\n"
"<property name=\"label\" translatable=\"yes\">Do nothing</property>\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">True</property>\n"
"<property name=\"receives_default\">False</property>\n"
"<property name=\"active\">True</property>\n"
"<property name=\"draw_indicator\">True</property>\n"
"<signal name=\"clicked\" handler=\"on_rbnothing_activate\" swapped=\"no\"/>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">0</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkRadioButton\" id=\"rbminimize\">\n"
"<property name=\"label\" translatable=\"yes\">Minimize</property>\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">True</property>\n"
"<property name=\"receives_default\">False</property>\n"
"<property name=\"draw_indicator\">True</property>\n"
"<property name=\"group\">rbnothing</property>\n"
"<signal name=\"clicked\" handler=\"on_rbminimize_activate\" swapped=\"no\"/>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">1</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkRadioButton\" id=\"rbhide\">\n"
"<property name=\"label\" translatable=\"yes\">Hide</property>\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">True</property>\n"
"<property name=\"receives_default\">False</property>\n"
"<property name=\"draw_indicator\">True</property>\n"
"<property name=\"group\">rbminimize</property>\n"
"<signal name=\"clicked\" handler=\"on_rbhide_activate\" swapped=\"no\"/>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">2</property>\n"
"</packing>\n"
"</child>\n"
"</object>\n"
"</child>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">2</property>\n"
"</packing>\n"
"</child>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">False</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"padding\">12</property>\n"
"<property name=\"position\">2</property>\n"
"</packing>\n"
"</child>\n"
"</object>\n"
"</child>\n"
"</object>\n"
"</child>\n"
"<child type=\"label\">\n"
"<object class=\"GtkLabel\" id=\"label73\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"label\" translatable=\"yes\">&lt;b&gt;Options&lt;/b&gt;</property>\n"
"<property name=\"use_markup\">True</property>\n"
"</object>\n"
"</child>\n"
"</object>\n"
"</child>\n"
"<child type=\"tab\">\n"
"<object class=\"GtkLabel\" id=\"label1\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"label\" translatable=\"yes\">General </property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"tab_fill\">False</property>\n"
"</packing>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkFrame\" id=\"frame1\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"border_width\">4</property>\n"
"<property name=\"label_xalign\">0</property>\n"
"<property name=\"shadow_type\">none</property>\n"
"<child>\n"
"<object class=\"GtkAlignment\" id=\"alignment1\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"top_padding\">12</property>\n"
"<property name=\"left_padding\">12</property>\n"
"<child>\n"
"<object class=\"GtkTreeView\" id=\"se_treeview\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">True</property>\n"
"<property name=\"model\">se_liststore</property>\n"
"<property name=\"headers_clickable\">False</property>\n"
"<property name=\"enable_search\">False</property>\n"
"<child>\n"
"<object class=\"GtkTreeViewColumn\" id=\"Visible\">\n"
"<property name=\"title\" translatable=\"yes\">Visible </property>\n"
"</object>\n"
"</child>\n"
"<child>\n"
"<object class=\"GtkTreeViewColumn\" id=\"Systems\">\n"
"<property name=\"title\" translatable=\"yes\">Systems </property>\n"
"<child>\n"
"<object class=\"GtkCellRendererText\" id=\"se_cellrenderertext\"/>\n"
"<attributes>\n"
"<attribute name=\"text\">0</attribute>\n"
"</attributes>\n"
"</child>\n"
"</object>\n"
"</child>\n"
"</object>\n"
"</child>\n"
"</object>\n"
"</child>\n"
"<child type=\"label\">\n"
"<object class=\"GtkLabel\" id=\"label5\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"label\" translatable=\"yes\">&lt;b&gt;Show In List&lt;/b&gt;</property>\n"
"<property name=\"use_markup\">True</property>\n"
"</object>\n"
"</child>\n"
"</object>\n"
"<packing>\n"
"<property name=\"position\">1</property>\n"
"</packing>\n"
"</child>\n"
"<child type=\"tab\">\n"
"<object class=\"GtkLabel\" id=\"label2\">\n"
"<property name=\"visible\">True</property>\n"
"<property name=\"can_focus\">False</property>\n"
"<property name=\"label\" translatable=\"yes\">Systems </property>\n"
"</object>\n"
"<packing>\n"
"<property name=\"position\">1</property>\n"
"<property name=\"tab_fill\">False</property>\n"
"</packing>\n"
"</child>\n"
"</object>\n"
"<packing>\n"
"<property name=\"expand\">True</property>\n"
"<property name=\"fill\">True</property>\n"
"<property name=\"position\">1</property>\n"
"</packing>\n"
"</child>\n"
"</object>\n"
"</child>\n"
"<action-widgets>\n"
"<action-widget response=\"0\">button1</action-widget>\n"
"</action-widgets>\n"
"</object>\n"
"</interface>\n"
;

#endif /* SETTINGS_GLADE_H */
